-- ============================================================
-- Seating schema — already included in 01_schema.sql
-- This file is kept for reference only.
-- See supabase/migrations/ for the authoritative migration history.
-- ============================================================
-- The seating tables (seating_tables, seats, seating_constraints,
-- room_config) were originally applied manually and are captured
-- in the baseline migration:
--   migrations/20260321000000_baseline_schema.sql
